name = "zarf"
type = "cli"

[platform.linux]
download-file = "zarf_v{version}_Linux_{arch}"

[platform.macos]
download-file = "zarf_v{version}_Darwin_{arch}"

[install]
download-url = "https://github.com/zarf-dev/zarf/releases/download/v{version}/{download_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/zarf-dev/zarf"
